### PR TITLE
Upgrade aws-sdk-go

### PR DESCRIPTION
**Pull request by rifelpet**
This adds support for the new af-south-1 and eu-south-1 regions

Ref: https://github.com/kubernetes/kops/issues/9012

### CODE REVIEW

**Comment by rifelpet** [comment]
@justinsb think we could get this in with the cert fix?

**Comment by rifelpet** [comment]
ah looks like i just missed 3.0.20200428 :)

**Comment by justinsb** [comment]
Yeah, looks like unfortunate timing.  We really need a (low-volume) slack room - I'll see if I can get one.

We could do a 20200429 release (technically I can even force it a day early).

**Comment by rifelpet** [comment]
consider holding for yet another new region https://aws.amazon.com/blogs/aws/now-open-aws-europe-milan-region/ waiting on a new aws-sdk-go release

**Comment by justinsb** [comment]
I've also realized that because kops itself won't support these new regions, we wouldn't necessarily backport it anyway (or at least, wouldn't backport it as far as the cert rotation fix).

So (inadvertently, perhaps) I think we've done the right thing by keeping 0428 minimal, we backport that as far as we can, then we do 0429 and don't backport it as far.

**Comment by rifelpet** [comment]
Updated to include both af-south-1 and eu-south-1

**Comment by justinsb** [comment]
Looks good - thanks @rifelpet 

/approve
/lgtm

**Pull request merged**
