### PR TITLE
Remove all versions for backups when using S3

### LINKED ISSUE #325: Backups are not really removed from versioned buckets
Kops uses versioned buckets for AWS and etcd-manager keeps the backups there.
The current way of removing backups is just a fake delete that marks the file as deleted, but all versions are kept and they count from cost point of view.

Clusters that are kept for longer periods of time or reuse the same bucket can end up with many TB of data stored because of this.

This will need a fix on the Kops side first:
https://github.com/kubernetes/kops/pull/9171

@justinsb

### PR DESCRIPTION
**Pull request by hakman**
Fixes #325

### CODE REVIEW

**Comment by hakman** [comment]
@justinsb @johngmyers

**Comment by justinsb** [comment]
Thanks for finding & fixing this.  Because this is existing behaviour (vs a regression), I propose we cut kops 1.16.3, 1.17.0 and then get this into the next 1.18 prerelease (likely this weekend).  Because we have the IAM changes already in 1.16.3 and 1.17.0, users can opt in, and then we can make it the default in 1.17.1 (and also in 1.16.4?)

**Comment by hakman** [comment]
Sounds good to me.
Maybe 1.18 can be beta.1 (I think it's time) and also cut the the branch for it.

**Comment by johngmyers** [comment]
Now that 1.16.3 and 1.17.0 have released perhaps we should update the vendoring.

**Comment by justinsb** [comment]
@johngmyers it's a good idea to pin to e.g. 1.17.0, I don't think it's going to change anything (I think) so I propose we do that in a follow-on PR, so we can start to get this tested e2e!

/approve
/lgtm

**Comment by justinsb** [comment]
I updated the vendored kops version in #329; doesn't seem to be any code changes to the VFS code directly, but looks like some other libraries get updated.

**Pull request merged**
