### PR TITLE
Update Go to 1.15.7

### PR DESCRIPTION
**Pull request by hakman**
... to match kOps.

### CODE REVIEW

**Comment by justinsb** [comment]
Looks good.  Any reason not to update rules-go to a newer version that recognizes the newer go version?

**Comment by hakman** [comment]
> Looks good. Any reason not to update rules-go to a newer version that recognizes the newer go version?

I guess not in `etcd-manager`. In kOps it was a problem with output path changes for binaries for which me and @rifelpet couldn't  find a simple solution.

**Comment by justinsb** [comment]
Ah - that makes sense.  Let's stick with what you've got here for now, for consistency then.

/approve
/lgtm

**Comment by justinsb** [comment]
Fix for the deprecation should be in #362

**Comment by justinsb** [comment]
I merged #362 - do you want to rebase and then I can cut a release?  Or should we leave this one till the next etcd-manager release?

**Comment by hakman** [comment]
Let's leave for next release please. Until then maybe we can do it in a nicer way, similar to https://github.com/kubernetes/kops/pull/10240.

**Comment by hakman** [comment]
@justinsb this should make things identical to kOps now.

**Comment by hakman** [comment]
@justinsb I think tis is now ready to go.

**Comment by justinsb** [comment]
@hakman do you think we should try to do this before kops 1.19.0?

**Comment by hakman** [comment]
@justinsb I think it may be safer to merge this after the new release for 1.19 and create a new release that we will use only on master for now. We will include it later in 1.19.1 if no issues are discovered.

**Comment by rifelpet** [comment]
Kops 1.19 is built with 1.15.4 for reference

**Comment by hakman** [comment]
Addressing that with https://github.com/kubernetes/kops/pull/10603.

**Comment by justinsb** [comment]
We discussed in "bonus" office hours that because we consider #391 to be important, we're going to merge this (with 1.15.7 IIRC) and test with #391, and so this will now make 1.19.0 :-)

**Comment by hakman** [comment]
And... success. Looks like both PRs passed the tests.

**Pull request merged**
